In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
type(arr1)

numpy.ndarray

In [4]:
arr1

array([1, 2, 3])

In [6]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
arr3 = np.array((1, 2, 3, 4, 5))
print(arr3)

[1 2 3 4 5]


In [13]:
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

[1 2 3]
(3,)
1
3
int64


In [15]:
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64
