In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
type(arr1)

numpy.ndarray

In [3]:
arr1

array([1, 2, 3])

In [4]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr3 = np.array((1, 2, 3, 4, 5))
print(arr3)

[1 2 3 4 5]


In [6]:
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

[1 2 3]
(3,)
1
3
int64


In [7]:
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9
int64


In [10]:
arrZ = np.zeros((2, 3), dtype=int) # Zeros array with 2 rows and 3 columns
print(arrZ)

[[0 0 0]
 [0 0 0]]


In [12]:
arrO = np.ones((3, 4)) # Ones array with 3 rows and 4 columns
print(arrO)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arrC = np.full((3, 8), 7, dtype=int)
print(arrC)

[[7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]]


In [14]:
arrI = np.eye(3, dtype=int) # Identity matrix 3x3
print(arrI)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
arr_0_5 = np.arange(6)  # Array with values 0 to 5
print(arr_0_5)

[0 1 2 3 4 5]


In [ ]:
arr_1_9 = np.arange(1, 10, 2) # array wth elements 1, 3, 5, 7, 9
print(arr_1_9)

[1 3 5 7 9]


In [17]:
arr_0_1 = np.linspace(0, 1, 5)
print(arr_0_1)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
arr_1_7 = np.linspace(1, 7, 14)
print(arr_1_7)

[1.         1.46153846 1.92307692 2.38461538 2.84615385 3.30769231
 3.76923077 4.23076923 4.69230769 5.15384615 5.61538462 6.07692308
 6.53846154 7.        ]


In [21]:
arr_0_and_1 = np.random.rand(2, 3)
print(arr_0_and_1)

[[0.53208815 0.47814513 0.07613123]
 [0.81618804 0.61032849 0.08576348]]


In [22]:
arrND = np.random.randn(2, 3)
print(arrND)

[[ 0.02381222  2.21513718  0.89731235]
 [-0.88890486  1.25318635 -0.0151971 ]]


In [23]:
arrRN = np.random.randint(0, 10, (2, 3))
print(arrRN)

[[4 8 0]
 [0 7 9]]


In [24]:
arrDT = np.array([1.2, 3.4, 5.6, 7.8])
arrDT_int = arrDT.astype(int)
print(arrDT_int)

[1 3 5 7]
