# Advanced Indexing, Sorting & Stacking

## 1. Conditional Selection (where)

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40])

In [4]:
result = np.where(arr > 25, 1, 0)
result

array([0, 0, 1, 1])

## 2. Extract Non-zero Elements

In [5]:
arr = np.array([0, 2, 0, 4, 5])
indices = np.nonzero(arr)
print(indices)
print(arr[indices])

(array([1, 3, 4]),)
[2 4 5]


## Sorting Arrays

In [6]:
arr = np.array([3, 1, 2])
np.sort(arr)

array([1, 2, 3])

In [7]:
arr2d = np.array([[3, 1, 2],
                [9, 8, 7]])
np.sort(arr2d, axis=1)

array([[1, 2, 3],
       [7, 8, 9]])

In [8]:
arr = np.array([3, 1, 2])
np.argsort(arr)

array([1, 2, 0])

## 4. Stacking Arrays

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [11]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])