# Numpy Indexing - Slicing and Reshaping

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])       # 10
print(arr[-1])      # 50

10
50


In [3]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0, 1])      # 2
print(arr2d[2, -1])     # 9

2
9


In [4]:
print(arr[1:4])     # [20, 30, 40]
print(arr[:3])      # [10, 20, 30]
print(arr[::2])     # [10, 30, 50]

[20 30 40]
[10 20 30]
[10 30 50]


In [5]:
print(arr2d[0:2, 1:3])  # Rows 0-1, Col 1-2  => [[2, 3], [5, 6]]

[[2 3]
 [5 6]]


In [6]:
print(arr2d[:, 0])      # Rist column: [1, 4, 7]

[1 4 7]


In [7]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print(mask)
print(arr[mask])

[False False False  True  True]
[4 5]


In [8]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(arr[indices])

[20 40 50]


In [9]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr2d[[0, 2], [1, 2]]

array([2, 9])

In [11]:
arr = np.arange(1, 7)    # [1, 2, 3, 4, 5, 6]
reshaped = arr.reshape((2, 3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2d_flattened = arr2d.flatten()

In [16]:
arr2d_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2d_flattened.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Adding / Removing Dimensions
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [20]:
arr_2d = arr[np.newaxis, :]
arr_2d

array([[1, 2, 3]])

In [22]:
arr_2d_col = arr[:, np.newaxis]
arr_2d_col

array([[1],
       [2],
       [3]])