# Array Operations & Broadcasting

## 1. Element-wise Arithmetic Operations

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
a + b

array([5, 7, 9])

In [4]:
a - b

array([-3, -3, -3])

In [5]:
a * b

array([ 4, 10, 18])

In [6]:
a / b

array([0.25, 0.4 , 0.5 ])

In [7]:
a ** 2

array([1, 4, 9])

In [8]:
a + 10

array([11, 12, 13])

In [9]:
a * 2

array([2, 4, 6])

## 2. Universal Functions

In [10]:
arr = np.array([1, 4, 9, 16])

In [11]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [12]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [13]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

In [14]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [15]:
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

## 3. Aggregation Functions

In [16]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [17]:
arr.sum()

np.int64(21)

In [18]:
arr.sum(axis=0)

array([5, 7, 9])

In [19]:
arr.sum(axis=1)

array([ 6, 15])

In [21]:
arr.mean()

np.float64(3.5)

In [22]:
arr.min()

np.int64(1)

In [23]:
arr.max()

np.int64(6)

In [24]:
arr.std()

np.float64(1.707825127659933)

## 4. Broadcasting

In [25]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
add_vector = np.array([10, 20, 30])
arr + add_vector

array([[11, 22, 33],
       [14, 25, 36]])

## 5. Comparison Operators

In [ ]:
arr = np.array([1, 2, 3, 4])

In [27]:
arr > 2

array([False, False,  True,  True])

In [28]:
arr == 3

array([False, False,  True, False])

## 6. Clipping Values

In [29]:
arr = np.array([1, 5, 8, 10])
np.clip(arr, 3, 8)

array([3, 5, 8, 8])